import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'bm-maroon': '#7A1A25',
        'bm-maroon-light': '#9A2B38',
        'bm-maroon-dark': '#60141D',
        'bm-gold': '#FFC72C',
        'bm-gold-dark': '#E6B328',
        'bm-gold-hover': '#e6b328',
        'bm-gold-light': '#FFF5D6',
        'bm-mint': '#E0F2F1',
        'bm-green-dark': '#004D40',
        'bm-white': '#FFFFFF',
        'bm-light-grey': '#F8FAFC',
        'bm-grey': '#E2E8F0',
        'bm-grey-dark': '#CFD8DC',
        'bm-text-primary': '#0F172A',
        'bm-text-secondary': '#475569',
        'bm-text-subtle': '#94A3B8',
        'bm-bg-light': '#F8F9FA',
        'bm-success': '#10B981',
        'bm-warning': '#F59E0B',
        'bm-danger': '#EF4444',
        'bm-info': '#3B82F6',
        'feedback-positive': '#16A34A',
        'feedback-positive-bg': '#F0FDF4',
        'feedback-warning': '#B45309',
        'feedback-warning-bg': '#FFFBEB',
        'feedback-neutral': '#C2410C',
        'feedback-neutral-bg': '#FFF7ED',
        'feedback-negative': '#DC2626',
        'feedback-negative-bg': '#FEF2F2',
        'score-green': '#10B981',
        'score-yellow': '#F59E0B',
        'score-red': '#EF4444',
        'brand-teams': '#6264A7',
        'brand-outlook': '#0078D4',
        'brand-gmail': '#EA4335',
        'brand-sheets': '#34A853',
        'brand-onedrive': '#0078D4',
        'brand-slack': '#4A154B',
        'brand-zoom': '#2D8CFF',
        'brand-notion': '#000000',
        'brand-trello': '#0079BF',
        'brand-salesforce': '#00A1E0',
        'brand-aws': '#FF9900',
        'brand-zapier': '#FF4A00',
      },
      fontFamily: {
        sans: ['Inter', 'var(--font-inter)', 'sans-serif'],
        display: ['Inter', 'var(--font-inter)', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        '2xl': '1.5rem',
      },
      boxShadow: {
        'soft': '0 4px 20px -2px rgba(0, 0, 0, 0.05)',
        'card': '0 0 0 1px rgba(0,0,0,0.03), 0 2px 8px rgba(0,0,0,0.04)',
        'card-hover': '0 0 0 1px rgba(122, 26, 37, 0.1), 0 8px 24px rgba(122, 26, 37, 0.08)',
        'glow': '0 0 15px rgba(255, 199, 44, 0.3)',
      },
      backgroundImage: {
        'gradient-card': 'linear-gradient(180deg, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 60%, #FFFFFF 100%)',
      },
          animation: {
            'blob': 'blob 7s infinite',
            'wave': 'wave 25s linear infinite',
            'wave-bars': 'wave 1.2s ease-in-out infinite',
            'fade-in-up': 'fadeInUp 1s cubic-bezier(0.16, 1, 0.3, 1) forwards',
            'fade-in': 'fadeIn 1.5s ease-out forwards',
            'shimmer': 'shimmer 2s infinite linear',
            'spin-slow': 'spin 20s linear infinite',
            'spin-reverse-slow': 'spin-reverse 25s linear infinite',
            'pulse-glow': 'pulseGlow 3s ease-in-out infinite',
            'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
            'float': 'float 6s ease-in-out infinite',
            'float-delayed': 'float 6s ease-in-out 3s infinite',
            'dash': 'dash 3s linear infinite',
            'ping-slow': 'ping 3s cubic-bezier(0, 0, 0.2, 1) infinite',
            'grow-graph': 'growGraph 3s ease-out forwards',
            'wander': 'wander 8s ease-in-out infinite',
            'wander-delayed': 'wander 10s ease-in-out 2s infinite',
            'slide-up': 'slideUp 0.5s ease-out forwards',
          },
      keyframes: {
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
        wave: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'spin-reverse': {
          'from': { transform: 'rotate(360deg)' },
          'to': { transform: 'rotate(0deg)' },
        },
        pulseGlow: {
          '0%, 100%': { opacity: '0.6', transform: 'scale(1)' },
          '50%': { opacity: '1', transform: 'scale(1.05)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        dash: {
          'to': { strokeDashoffset: '-100' },
        },
        growGraph: {
          '0%': { strokeDasharray: '0, 1000' },
          '100%': { strokeDasharray: '1000, 0' },
        },
            wander: {
              '0%, 100%': { transform: 'translate(0, 0) rotate(0deg)' },
              '25%': { transform: 'translate(10px, -15px) rotate(5deg)' },
              '50%': { transform: 'translate(-10px, -20px) rotate(-5deg)' },
              '75%': { transform: 'translate(15px, -10px) rotate(3deg)' },
            },
            waveHeight: {
              '0%, 100%': { height: '20%' },
              '50%': { height: '100%' },
            },
            slideUp: {
              '0%': { opacity: '0', transform: 'translateY(20px)' },
              '100%': { opacity: '1', transform: 'translateY(0)' },
            },
          },
        },
      },
      plugins: [],
    }
export default config

