import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'bm-maroon': '#7A1A25',
        'bm-maroon-light': '#9A2B38',
        'bm-maroon-dark': '#60141D',
        'bm-gold': '#FFC72C',
        'bm-gold-dark': '#E6B328',
        'bm-gold-hover': '#e6b328',
        'bm-gold-light': '#FFF5D6',
        'bm-mint': '#E0F2F1',
        'bm-green-dark': '#004D40',
        'bm-white': '#FFFFFF',
        'bm-light-grey': '#F7F8FA',
        'bm-grey': '#E9ECF0',
        'bm-grey-dark': '#CFD5DB',
        'bm-text-primary': '#111827',
        'bm-text-secondary': '#4B5563',
        'bm-text-subtle': '#6B7280',
        'bm-bg-light': '#F8F9FA',
        'bm-success': '#10B981',
        'bm-warning': '#F59E0B',
        'bm-danger': '#EF4444',
        'bm-info': '#3B82F6',
        'feedback-positive': '#16A34A',
        'feedback-positive-bg': '#F0FDF4',
        'feedback-warning': '#B45309',
        'feedback-warning-bg': '#FFFBEB',
        'feedback-neutral': '#C2410C',
        'feedback-neutral-bg': '#FFF7ED',
        'feedback-negative': '#DC2626',
        'feedback-negative-bg': '#FEF2F2',
        'score-green': '#10B981',
        'score-yellow': '#F59E0B',
        'score-red': '#EF4444',
        'brand-teams': '#6264A7',
        'brand-outlook': '#0078D4',
        'brand-gmail': '#EA4335',
        'brand-sheets': '#34A853',
        'brand-onedrive': '#0078D4',
        'brand-slack': '#4A154B',
        'brand-zoom': '#2D8CFF',
        'brand-notion': '#000000',
        'brand-trello': '#0079BF',
        'brand-salesforce': '#00A1E0',
        'brand-aws': '#FF9900',
        'brand-zapier': '#FF4A00',
      },
      fontFamily: {
        sans: ['Inter', 'var(--font-inter)', 'sans-serif'],
        display: ['Inter', 'var(--font-inter)', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        '2xl': '2rem',
      },
      boxShadow: {
        'soft': '0 4px 15px 0 rgba(0, 0, 0, 0.03)',
        'card': '0 2px 12px 0 rgba(122, 26, 37, 0.05)',
        'card-hover': '0 12px 30px -8px rgba(122, 26, 37, 0.15)',
        'glow': '0 0 15px rgba(255, 199, 44, 0.3)',
        'premium': '0 4px 20px -2px rgba(122, 26, 37, 0.08), 0 2px 8px -2px rgba(0, 0, 0, 0.04)',
        'node-active': '0 0 0 2px #7A1A25, 0 8px 30px rgba(122, 26, 37, 0.15)',
        'node-hover': '0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 0 0 1px rgba(122, 26, 37, 0.1)',
        'card-depth': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)',
      },
      backgroundImage: {
        'gradient-card': 'linear-gradient(180deg, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 60%, #FFFFFF 100%)',
        'dot-pattern': 'radial-gradient(#E5E7EB 1px, transparent 1px)',
      },
      backgroundSize: {
        'grid': '20px 20px',
      },
      animation: {
        'fade-in-up': 'fadeInUp 1s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in': 'fadeIn 0.5s ease-out forwards',
        'slide-up': 'slideUp 0.6s ease-out forwards',
        'shimmer': 'shimmer 2s infinite linear',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'flow-dash': 'flowDash 1.5s linear infinite',
        'draw-chart': 'drawChart 2s ease-out forwards',
        'scale-in': 'scaleIn 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275) forwards',
        'grow-width': 'growWidth 1s ease-out forwards',
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        flowDash: {
          '0%': { strokeDashoffset: '24' },
          '100%': { strokeDashoffset: '0' },
        },
        drawChart: {
          '0%': { strokeDasharray: '1000', strokeDashoffset: '1000' },
          '100%': { strokeDasharray: '1000', strokeDashoffset: '0' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        growWidth: {
          '0%': { width: '0%' },
          '100%': { width: '100%' },
        },
      },
    },
  },
  plugins: [],
}
export default config
